# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='match_service.proto',
  package='match_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13match_service.proto\x12\rmatch_service\"L\n\x12\x43reateMatchRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\"\"\n\x10\x43reateMatchReply\x12\x0e\n\x06status\x18\x01 \x01(\t2a\n\x0cMatchService\x12Q\n\x0b\x43reateMatch\x12!.match_service.CreateMatchRequest\x1a\x1f.match_service.CreateMatchReplyb\x06proto3'
)




_CREATEMATCHREQUEST = _descriptor.Descriptor(
  name='CreateMatchRequest',
  full_name='match_service.CreateMatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='match_service.CreateMatchRequest.sender_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='match_service.CreateMatchRequest.receiver_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='match_service.CreateMatchRequest.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=114,
)


_CREATEMATCHREPLY = _descriptor.Descriptor(
  name='CreateMatchReply',
  full_name='match_service.CreateMatchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='match_service.CreateMatchReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['CreateMatchRequest'] = _CREATEMATCHREQUEST
DESCRIPTOR.message_types_by_name['CreateMatchReply'] = _CREATEMATCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateMatchRequest = _reflection.GeneratedProtocolMessageType('CreateMatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMATCHREQUEST,
  '__module__' : 'match_service_pb2'
  # @@protoc_insertion_point(class_scope:match_service.CreateMatchRequest)
  })
_sym_db.RegisterMessage(CreateMatchRequest)

CreateMatchReply = _reflection.GeneratedProtocolMessageType('CreateMatchReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMATCHREPLY,
  '__module__' : 'match_service_pb2'
  # @@protoc_insertion_point(class_scope:match_service.CreateMatchReply)
  })
_sym_db.RegisterMessage(CreateMatchReply)



_MATCHSERVICE = _descriptor.ServiceDescriptor(
  name='MatchService',
  full_name='match_service.MatchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateMatch',
    full_name='match_service.MatchService.CreateMatch',
    index=0,
    containing_service=None,
    input_type=_CREATEMATCHREQUEST,
    output_type=_CREATEMATCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATCHSERVICE)

DESCRIPTOR.services_by_name['MatchService'] = _MATCHSERVICE

# @@protoc_insertion_point(module_scope)
