version: "3.8"

services:
  cms-admin:
    container_name: cms_admin
    build: ./CmsAdmin
    # entrypoint: ["./entrypoint.sh"]
    ports:
      - "8002:8000"
    volumes:
      - staticdata:/code/staticfiles
    env_file: ./CmsAdmin/config/envs/dev.env

  interactive-service:
    container_name: interactive-service
    build:
      context: ./interactive_main_service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
      - "50051:50051"

networks:
  default:
    external:
      name: sn_network
volumes:
  staticdata:
