version: "3.8"

services:
  cms-admin:
    container_name: cms_admin
    build: ./CmsAdmin
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8002:8000"
    volumes:
      - staticdata:/code/staticfiles

    command: gunicorn CmsAdmin.wsgi:application --bind 0.0.0.0:8000 --workers=4
  core-service:
    container_name: core_service
    build: ./SocialNetworkBackend
    ports:
      - "8081:8080"
    expose:
      - 8080

  nginx:
    container_name: sn_nginx
    build: ./nginx
    restart: always
    volumes:
      - staticdata:/code/staticfiles
    ports:
      - $NGINX_PORT:80
    depends_on:
      - cms-admin
      - core-service

volumes:
  staticdata:
