# Generated by Django 2.2.16 on 2020-09-21 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0004_event_userevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('own_reaction', models.IntegerField(blank=True, help_text='User feeling', null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.IntegerField(default=1, help_text='type hide from timeline')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_content.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommentPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(max_length=500)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_content.UserCommentPost')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
