# Generated by Django 2.2.16 on 2020-09-26 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0005_post_usercommentpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('target_react_id', models.UUIDField()),
                ('type', models.IntegerField(help_text='love or live')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
