# Generated by Django 2.2.16 on 2020-10-22 16:28

from django.db import migrations, models
import django.db.models.deletion
import user_content.domain.models.access_token
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0006_userreact'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'ADMIN'), (2, 'SYS_ADMIN')], default=0),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scopes', models.CharField(blank=True, default='[]', max_length=250, null=True)),
                ('iss', models.CharField(blank=True, default='network-social', max_length=100, null=True)),
                ('exp', models.BigIntegerField(blank=True, default=user_content.domain.models.access_token.token_expiry, null=True)),
                ('iat', models.BigIntegerField(blank=True, default=user_content.domain.models.access_token.current_time, null=True)),
                ('nbf', models.BigIntegerField(blank=True, default=user_content.domain.models.access_token.current_time, null=True)),
                ('device_name', models.CharField(blank=True, max_length=250, null=True)),
                ('os', models.CharField(blank=True, choices=[('IOS', 'Ios'), ('WEB', 'Web'), ('ANDROID', 'Android')], default='WEB', max_length=10, null=True)),
                ('os_version', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'IN_ACTIVE'), (2, 'BLACK_LIST')], default=0)),
                ('sub', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
