# Generated by Django 2.2.16 on 2020-11-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0007_auto_20201022_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
