# Generated by Django 2.2.16 on 2020-11-28 08:39

import core.domain.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0008_auto_20201128_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercommentpost',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreact',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
    ]
