# Generated by Django 2.2.16 on 2020-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0009_auto_20201128_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Married')], help_text='Marital status: 0 - Single, 1 - Got married', null=True),
        ),
    ]
