# Generated by Django 2.2.16 on 2020-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0010_auto_20201128_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=1),
        ),
    ]
