# Generated by Django 2.2.16 on 2020-12-05 05:47

from django.db import migrations, models
import user_content.domain.enums.react_type_enum


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0013_auto_20201205_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreactpost',
            name='type',
            field=models.IntegerField(choices=[(0, 'Like'), (1, 'Love')], default=user_content.domain.enums.react_type_enum.ReactTypeEnum(0), help_text='love or live'),
        ),
    ]
