# Generated by Django 2.2.16 on 2020-12-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0014_auto_20201205_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreactpost',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account', unique=True),
        ),
    ]
