# Generated by Django 2.2.16 on 2020-12-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0015_auto_20201205_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreactpost',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
