# Generated by Django 2.2.16 on 2020-12-05 06:58

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0017_auto_20201205_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReactComment',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Like'), (1, 'Love')], default=0, help_text='love or like')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.UserCommentPost')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'db_table': 'user_react_comment',
                'unique_together': {('comment', 'sender')},
            },
        ),
    ]
