# Generated by Django 2.2.16 on 2020-12-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0018_userreactcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(through='user_content.UserFollow', to='user_content.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('source', 'target')},
        ),
    ]
