# Generated by Django 2.2.16 on 2020-12-05 10:26

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0019_auto_20201205_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryViewer',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('react_type', models.IntegerField(blank=True, choices=[(0, 'Like'), (1, 'Love')], null=True)),
            ],
            options={
                'db_table': 'user_content_story_viewer',
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
                ('viewers', models.ManyToManyField(related_name='story_viewers', through='user_content.StoryViewer', to='user_content.Account')),
            ],
            options={
                'db_table': 'user_content_user_story',
            },
        ),
        migrations.AddField(
            model_name='storyviewer',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.UserStory'),
        ),
        migrations.AddField(
            model_name='storyviewer',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='storyviewer',
            unique_together={('story', 'viewer')},
        ),
    ]
