# Generated by Django 2.2.16 on 2020-12-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0020_auto_20201205_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
