# Generated by Django 2.2.16 on 2021-01-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0023_auto_20201214_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='following_users',
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='source',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='target',
        ),
    ]
