# Generated by Django 2.2.16 on 2021-01-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0024_auto_20210123_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(through='user_content.UserFollow', to='user_content.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='following_users',
            field=models.ManyToManyField(related_name='following_user_relate', through='user_content.UserFollow', to='user_content.Account'),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_follow', to='user_content.Account'),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_follow', to='user_content.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('source', 'target')},
        ),
    ]
