# Generated by Django 2.2.16 on 2021-01-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0025_auto_20210123_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(max_length='36', on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
