# Generated by Django 2.2.16 on 2021-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0026_auto_20210123_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(1, 'PostTypeEnum.ACTIVE'), (0, 'PostTypeEnum.HIDDEN')], default=1, help_text='type hide from timeline'),
        ),
    ]
