# Generated by Django 2.2.16 on 2021-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0027_auto_20210123_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'HIDDEN')], default=1, help_text='type hide from timeline'),
        ),
    ]
