# Generated by Django 2.2.16 on 2021-01-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0028_auto_20210123_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(blank=True, max_length=36, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
