# Generated by Django 2.2.16 on 2021-02-06 18:05

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0029_post_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerify',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('front_photo_url', models.TextField(blank=True, null=True)),
                ('back_photo_url', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'PENDING'), (1, 'VERIFIED'), (-1, 'REJECTED')], default=0, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'db_table': 'uc_account_virifies',
            },
        ),
    ]
