# Generated by Django 2.2.16 on 2021-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0030_accountverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'ACTIVE'), (0, 'DEACTIVE'), (2, 'BANNED')], default=1, null=True),
        ),
    ]
