# Generated by Django 2.2.16 on 2021-02-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0032_accountreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'RESOLVED'), (0, 'UN_RESOLVED')], default=0, null=True),
        ),
    ]
