# Generated by Django 2.2.16 on 2021-02-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0033_accountreport_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountreport',
            unique_together={('sender', 'receiver', 'related_post')},
        ),
    ]
