# Generated by Django 2.2.16 on 2021-02-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0034_auto_20210208_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account_reports', to='user_content.Account'),
        ),
        migrations.AlterField(
            model_name='accountreport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account_reports', to='user_content.Account'),
        ),
    ]
