# Generated by Django 2.2.16 on 2021-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0036_account_reporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reason_dating',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
