# Generated by Django 2.2.16 on 2021-02-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0004_auto_20210130_1344'),
        ('user_content', '0037_profile_reason_dating'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='medias',
            field=models.ManyToManyField(through='media_content.MediaCollection', to='media_content.Media'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_content.Profile'),
        ),
        migrations.AlterModelTable(
            name='collection',
            table='uc_collections',
        ),
    ]
