# Generated by Django 2.2.16 on 2021-02-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0038_auto_20210211_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='profile',
        ),
    ]
