# Generated by Django 2.2.16 on 2021-02-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0039_remove_collection_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_content.Profile'),
        ),
    ]
