# Generated by Django 2.2.16 on 2021-02-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0040_collection_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverify',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
