# Generated by Django 2.2.16 on 2021-02-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0041_auto_20210217_0954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountverify',
            table='uc_account_verifies',
        ),
    ]
