# Generated by Django 2.2.16 on 2021-02-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0042_auto_20210217_1000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountreport',
            unique_together=set(),
        ),
    ]
