# Generated by Django 2.2.16 on 2021-02-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0043_auto_20210218_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reporting_users',
            field=models.ManyToManyField(related_name='account_reporting_relate', through='user_content.AccountReport', to='user_content.Account'),
        ),
    ]
