# Generated by Django 2.2.16 on 2021-02-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0044_account_reporting_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreactpost',
            unique_together={('post',)},
        ),
        migrations.RemoveField(
            model_name='userreactpost',
            name='sender',
        ),
    ]
