# Generated by Django 2.2.16 on 2021-02-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0045_auto_20210222_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreactpost',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='userreactpost',
            unique_together={('post', 'sender')},
        ),
    ]
