# Generated by Django 2.2.16 on 2020-12-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_auto_20201128_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaMessage',
        ),
    ]
