# Generated by Django 2.2.16 on 2021-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0003_delete_mediamessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.IntegerField(choices=[(1, 'VIDEO'), (0, 'PHOTO')], help_text='1- video, 0- photo'),
        ),
    ]
