# Generated by Django 2.2.16 on 2020-09-21 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_content', '0005_post_usercommentpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('general_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nick_name', models.CharField(max_length=36)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_management.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
