# Generated by Django 2.2.16 on 2020-11-28 08:39

import core.domain.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='id',
            field=models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False),
        ),
    ]
