# Generated by Django 2.2.16 on 2020-12-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0003_auto_20201128_0839'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='cm_room',
        ),
    ]
