# Generated by Django 2.2.16 on 2020-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0004_auto_20201214_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='general_name',
            field=models.CharField(db_column='generalName', max_length=100),
        ),
    ]
