# Generated by Django 2.2.16 on 2020-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0005_auto_20201214_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='nick_name',
            field=models.CharField(db_column='nickName', max_length=36),
        ),
        migrations.AlterModelTable(
            name='message',
            table='cm_message',
        ),
        migrations.AlterModelTable(
            name='userroom',
            table='cm_user_room',
        ),
    ]
