# Generated by Django 2.2.16 on 2020-12-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0006_auto_20201214_0622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='cm_messages',
        ),
        migrations.AlterModelTable(
            name='room',
            table='cm_rooms',
        ),
        migrations.AlterModelTable(
            name='userroom',
            table='cm_user_rooms',
        ),
    ]
