# Generated by Django 2.2.16 on 2020-12-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0007_auto_20201214_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
    ]
