# Generated by Django 2.2.16 on 2020-12-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0008_auto_20201214_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account'),
        ),
        migrations.AlterField(
            model_name='room',
            name='general_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='nick_name',
            field=models.CharField(max_length=36),
        ),
    ]
