# Generated by Django 2.2.16 on 2020-12-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0009_auto_20201214_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
