# Generated by Django 2.2.16 on 2020-12-26 11:37

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0012_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactSmartRoom',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'HATE'), (1, 'LOVE')], default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_management.Room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_management.UserRoom')),
            ],
            options={
                'db_table': 'cm_react_smart_rooms',
                'unique_together': {('room', 'sender')},
            },
        ),
    ]
