# Generated by Django 2.2.16 on 2020-12-26 12:08

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0023_auto_20201214_0758'),
        ('chat_management', '0013_reactsmartroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'CLOSE'), (1, 'LOVE'), (2, 'SUPER_LOVE')], default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_receiver_related', to='user_content.Account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sender_related', to='user_content.Account')),
            ],
            options={
                'db_table': 'cm_matches',
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
