# Generated by Django 2.2.16 on 2020-12-27 08:10

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0023_auto_20201214_0758'),
        ('chat_management', '0015_mediamessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSetting',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('max_distance', models.IntegerField(blank=True, default=10, help_text='Max distance in km', null=True)),
                ('min_age', models.IntegerField(blank=True, default=18, help_text='Min age', null=True)),
                ('max_age', models.IntegerField(blank=True, default=21, help_text='Max age', null=True)),
                ('target_gender', models.IntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'UN_KNOWN')], default=0, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_content.Account')),
            ],
            options={
                'db_table': 'cm_match_settings',
            },
        ),
    ]
