# Generated by Django 2.2.16 on 2021-01-01 09:43

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0023_auto_20201214_0758'),
        ('chat_management', '0016_matchsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapper',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=300, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'UN_KNOWN')], null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ref_account', to='user_content.Account')),
            ],
            options={
                'db_table': 'cm_account_mapper',
            },
        ),
    ]
