# Generated by Django 2.2.16 on 2021-01-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0018_auto_20210101_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='receiver_mapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_mapper_receiver_related', to='chat_management.AccountMapper'),
        ),
        migrations.AddField(
            model_name='match',
            name='sender_mapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_sender_related', to='chat_management.AccountMapper'),
        ),
        migrations.AddField(
            model_name='matchsetting',
            name='account_mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_management.AccountMapper'),
        ),
        migrations.AddField(
            model_name='userroom',
            name='account_mapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_management.AccountMapper'),
        ),
        migrations.AlterField(
            model_name='match',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mapper_receiver_related', to='user_content.Account'),
        ),
    ]
