# Generated by Django 2.2.16 on 2021-01-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0020_run_account_chat_20210101_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsetting',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='account',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sender',
        ),
    ]
