# Generated by Django 2.2.16 on 2021-01-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0022_auto_20210101_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapper',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ref_account', to='user_content.Account'),
        ),
    ]
