# Generated by Django 2.2.16 on 2021-01-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0023_auto_20210101_1027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountmapper',
            table='cm_account_mappers',
        ),
    ]
