# Generated by Django 2.2.16 on 2021-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0024_auto_20210101_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='room',
        ),
    ]
