# Generated by Django 2.2.16 on 2021-01-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0025_remove_userroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_management.Room'),
        ),
    ]
