# Generated by Django 2.2.16 on 2021-02-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0026_userroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapper',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='accountmapper',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='accountmapper',
            name='job',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='accountmapper',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
