# Generated by Django 2.2.16 on 2021-02-11 08:50

import core.domain.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0027_auto_20210211_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAccount',
            fields=[
                ('id', models.CharField(default=core.domain.models.base_model.pkgen, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('media_url', models.CharField(max_length=300)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'VIDEO'), (1, 'PHOTO')], default=1, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_management.AccountMapper')),
            ],
            options={
                'db_table': 'cm_media_accounts',
            },
        ),
    ]
