# Generated by Django 2.2.16 on 2021-02-15 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0028_mediaaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapper',
            name='ref',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_ref_account', to='user_content.Account'),
        ),
    ]
