# Generated by Django 2.2.16 on 2021-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0029_auto_20210215_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'SMART'), (2, 'MATCH'), (-1, 'SMART_PENDING')], default=0),
        ),
    ]
